theme: jekyll-theme-architect

title: Sarah Harrison's Portfolio
description: Below are some examples of my work in Python. There are some code example and well as some demo video I have made for other students in a class I was taking.
